package ma.eni.fr.europcar.enums;

/**
 * Created by Administrateur on 10/04/2018.
 */

public enum Message
{
    PARAMETRES_AGENCE,
    CONNEXION_REUSSIE,
    CONNEXION,
    INSCRIPTION_REUSSIE,
    INSCRIPTION,
    LOCATION_RENDUE,
    EMAIL_NON_RENSEIGNE,
    MOT_DE_PASSE_NON_RENSEIGNE,
    MOT_DE_PASSE_CONFIRMATION_NON_RENSEIGNE,
    MOT_DE_PASSE_CONFIRMATION_ERREUR,
    EST_ENDOMMAGEE_NON_RENSEIGNE,
    PLEIN_FAIT_NON_RENSEIGNE,
    KMS_NON_RENSEIGNE,
    KMS_ERREUR,
    TOKEN_NON_RENSEIGNE,
    RAISON_SOCIALE_NON_RENSEIGNE,
    SIRET_NON_RENSEIGNE,
    SIRET_ERREUR,
    VOIE_NON_RENSEIGNE,
    CODE_POSTAL_NON_RESEIGNE,
    CODE_POSTAL_ERREUR,
    VILLE_NON_RENSEIGNE,
}